package manifest

// Manifest is the human-editable contract between river-manifest and River.
// It intentionally contains semantic identities only. Runtime addresses and
// uprobe offsets are rebuilt from the ELF each time River starts.
type Manifest struct {
	Version  uint32   `yaml:"version" json:"version"`
	Artifact Artifact `yaml:"artifact" json:"artifact"`
	Settings Settings `yaml:"settings" json:"settings"`
	Models   []Model  `yaml:"models" json:"models"`
}

type Artifact struct {
	Binary            string   `yaml:"binary" json:"binary"`
	BuildID           string   `yaml:"build_id" json:"build_id"`
	DescriptorSources []string `yaml:"descriptor_sources,omitempty" json:"descriptor_sources,omitempty"`
	// DescriptorSource is retained only to read manifests generated by older
	// River versions, which could record at most one Code Descriptor source.
	DescriptorSource string `yaml:"descriptor_source,omitempty" json:"descriptor_source,omitempty"`
}

type Settings struct {
	Cycles      uint32 `yaml:"cycles" json:"cycles"`
	SampleEvery uint32 `yaml:"sample_every" json:"sample_every"`
}

type Model struct {
	Name          string    `yaml:"name" json:"name"`
	Selected      bool      `yaml:"selected" json:"selected"`
	Hooks         HookRoles `yaml:"hooks" json:"hooks"`
	PossibleHooks []Hook    `yaml:"possible_hooks" json:"possible_hooks"`
	Inputs        []Data    `yaml:"inputs,omitempty" json:"inputs,omitempty"`
	Outputs       []Data    `yaml:"outputs,omitempty" json:"outputs,omitempty"`
	States        []Data    `yaml:"states,omitempty" json:"states,omitempty"`
}

type HookRoles struct {
	InputWrite string `yaml:"input_write" json:"input_write"`
	StateWrite string `yaml:"state_write" json:"state_write"`
	Sample     string `yaml:"sample" json:"sample"`
}

type Hook struct {
	ID           string   `yaml:"id" json:"id"`
	Function     string   `yaml:"function" json:"function"`
	Phase        string   `yaml:"phase" json:"phase"`
	AllowedRoles []string `yaml:"allowed_roles,omitempty" json:"allowed_roles,omitempty"`
}

type Data struct {
	Name          string `yaml:"name" json:"name"`
	Path          string `yaml:"path" json:"path"`
	GraphicalName string `yaml:"graphical_name,omitempty" json:"graphical_name,omitempty"`
	SID           string `yaml:"sid,omitempty" json:"sid,omitempty"`
	Category      string `yaml:"category,omitempty" json:"category,omitempty"`
	Type          string `yaml:"type" json:"type"`
	Selected      bool   `yaml:"selected" json:"selected"`
	Supported     bool   `yaml:"supported" json:"supported"`
	Writable      bool   `yaml:"writable" json:"writable"`
	Reason        string `yaml:"reason,omitempty" json:"reason,omitempty"`
}

type RuntimePlan struct {
	Binary      string
	BuildID     string
	Cycles      uint32
	SampleEvery uint32
	Models      []RuntimeModel
	StateByName map[string]RuntimeData
}

type RuntimeModel struct {
	ID             uint32
	Name           string
	StepSymbol     string
	InputWriteHook RuntimeHook
	StateWriteHook RuntimeHook
	SampleHook     RuntimeHook
	Inputs         []RuntimeData
	Outputs        []RuntimeData
	States         []RuntimeData
}

type RuntimeHook struct {
	ID       string
	Symbol   string
	Function string
	Phase    string
}

type RuntimeData struct {
	ID            uint32
	ModelID       uint32
	Name          string
	GraphicalName string
	Path          string
	Category      string
	Type          PrimitiveType
	Base          BaseKind
	Offset        int64
	Writable      bool
}

type BaseKind uint8

const (
	BaseThis BaseKind = iota + 1
	BaseELF
)

type PrimitiveType struct {
	Name     string
	Size     uint8
	Signed   bool
	Floating bool
	Boolean  bool
}
